services:

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama-startup.sh:/startup.sh:ro
    entrypoint: ["/bin/sh", "/startup.sh"]
    restart: unless-stopped

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  fastapi-backend:
    build:
      context: ./server
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    restart: unless-stopped


volumes:
  ollama_data:
  open-webui:
